/*
 *     Copyright 2021 Mersin İl Milli Eğitim Müdürlüğü Ölçme Değerlendirme Merkezi
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 29-Mar-2021 15:05:58 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `choices` CASCADE
;

DROP TABLE IF EXISTS `circullum` CASCADE
;

DROP TABLE IF EXISTS `cq_info` CASCADE
;

DROP TABLE IF EXISTS `ei_infos` CASCADE
;

DROP TABLE IF EXISTS `eq_infos` CASCADE
;

DROP TABLE IF EXISTS `exam_type` CASCADE
;

DROP TABLE IF EXISTS `exams` CASCADE
;

DROP TABLE IF EXISTS `groups` CASCADE
;

DROP TABLE IF EXISTS `ig_infos` CASCADE
;

DROP TABLE IF EXISTS `institutions` CASCADE
;

DROP TABLE IF EXISTS `lessons` CASCADE
;

DROP TABLE IF EXISTS `programs` CASCADE
;

DROP TABLE IF EXISTS `questions` CASCADE
;

DROP TABLE IF EXISTS `sc_infos` CASCADE
;

DROP TABLE IF EXISTS `settings` CASCADE
;

DROP TABLE IF EXISTS `students` CASCADE
;

/* Create Tables */

CREATE TABLE `choices`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` NVARCHAR(6000) NULL,
	`is_correct` BOOL NULL,
	`q_id` BIGINT UNSIGNED NULL,
	CONSTRAINT `PK_choices` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `circullum`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`lesson_id` BIGINT UNSIGNED NULL,
	`parent_id` BIGINT UNSIGNED NULL,
	`code` NVARCHAR(50) NULL,
	`level` TINYINT NULL,
	`type` TINYINT NULL COMMENT 'Ünite, Konu, Kazanım ayrımı için eklendi
	Ünite:0, Konu:1, Kazanım, 2',
	`content` NVARCHAR(6000) NULL,
	CONSTRAINT `PK_circullum` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `cq_info`
(
	`c_id` BIGINT UNSIGNED NOT NULL,
	`q_id` BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `PK_cq_info` PRIMARY KEY (`c_id` ASC, `q_id` ASC)
)

;

CREATE TABLE `ei_infos`
(
	`e_id` BIGINT UNSIGNED NOT NULL,
	`i_id` BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `PK_ei_infos` PRIMARY KEY (`e_id` ASC, `i_id` ASC)
)

;

CREATE TABLE `eq_infos`
(
	`lesson_id` BIGINT UNSIGNED NOT NULL,
	`exam_id` BIGINT UNSIGNED NOT NULL,
	`count` INT UNSIGNED NULL,
	CONSTRAINT `PK_eq_info` PRIMARY KEY (`exam_id` ASC, `lesson_id` ASC)
)

;

CREATE TABLE `exam_type`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`code` NVARCHAR(100) NULL,
	`name` NVARCHAR(6000) NULL,
	CONSTRAINT `PK_exam_type` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `exams`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`type_id` BIGINT UNSIGNED NULL,
	`title` NVARCHAR(500) NULL,
	`code` NVARCHAR(20) NULL,
	`description` NVARCHAR(10000) NULL,
	CONSTRAINT `PK_Table A` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `groups`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` NVARCHAR(6000) NULL,
	`code` VARCHAR(50) NULL,
	`created_at` TIMESTAMP NULL,
	`updated_at` TIMESTAMP NULL,
	CONSTRAINT `PK_groups` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `ig_infos`
(
	`g_id` BIGINT UNSIGNED NOT NULL,
	`i_id` BIGINT UNSIGNED NOT NULL,
	CONSTRAINT `PK_ig_infos` PRIMARY KEY (`g_id` ASC, `i_id` ASC)
)

;

CREATE TABLE `institutions`
(
	`id` BIGINT UNSIGNED NOT NULL,
	`parent_id` BIGINT NULL,
	`district_id` INT UNSIGNED NULL,
	`name` NVARCHAR(6000) NULL,
	`phone` NVARCHAR(15) NULL,
	`address` NVARCHAR(6000) NULL,
	`e_mail` NVARCHAR(250) NULL,
	CONSTRAINT `PK_institutions` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `lessons`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` NVARCHAR(1000) NULL,
	`code` NVARCHAR(100) NULL,
	CONSTRAINT `PK_lessons` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `programs`
(
	`id` BIGINT NOT NULL,
	`name` NVARCHAR(250) NULL,
	`code` NVARCHAR(100) NULL,
	CONSTRAINT `PK_programs` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `questions`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`type` TINYINT NULL DEFAULT 0 COMMENT 'Çoktan Seçmeli:0
	Açık uçlu:1
	D/Y: 2
	Boşluk dolduma:3
	Eşleştirme: 4',
	`context` NVARCHAR(6000) NULL COMMENT 'Ortak köklü maddlerde madde kökü ortak kök, Soru bağlamı, öncül',
	`body` NVARCHAR(6000) NULL,
	`parent_id` BIGINT NULL,
	`creator_id` BIGINT NULL,
	CONSTRAINT `PK_questions` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `sc_infos`
(
	`s_id` BIGINT UNSIGNED NOT NULL COMMENT 'student id',
	`c_id` BIGINT UNSIGNED NOT NULL COMMENT 'choice id',
	`e_id` BIGINT UNSIGNED NOT NULL COMMENT 'exam id',
	`q_id` BIGINT UNSIGNED NOT NULL
)

;

CREATE TABLE `settings`
(
	`inst_name` VARCHAR(50) NULL,
	`web_address` VARCHAR(50) NULL,
	`twitter_address` VARCHAR(50) NULL,
	`facebook_address` VARCHAR(50) NULL
)

;

CREATE TABLE `students`
(
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`full_name` NVARCHAR(250) NULL,
	`level` TINYINT NULL,
	`no` INT UNSIGNED NULL,
	`inst_id` BIGINT UNSIGNED NULL,
	`branch` NVARCHAR(50) NULL,
	CONSTRAINT `PK_students` PRIMARY KEY (`id` ASC)
)

;

alter table choices
    add created_at timestamp null,
    add updated_at timestamp null;

alter table circullum
    add created_at timestamp null,
    add updated_at timestamp null;

alter table cq_info
    add created_at timestamp null,
    add updated_at timestamp null;

alter table ei_infos
    add created_at timestamp null,
    add updated_at timestamp null;

alter table eq_infos
    add created_at timestamp null,
    add updated_at timestamp null;

alter table exam_type
    add created_at timestamp null,
    add updated_at timestamp null;

alter table exams
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `ig_infos`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `institutions`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `lessons`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `programs`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `questions`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `sc_infos`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `settings`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table `students`
    add created_at timestamp null,
    add updated_at timestamp null;

alter table exams
    add creator_id bigint unsigned null after id;

alter table exams
    add start_date datetime null after code,
    add end_date datetime null after start_date;


/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `choices` 
 ADD INDEX `IXFK_choices_questions` (`q_id` ASC)
;

ALTER TABLE `circullum` 
 ADD INDEX `IXFK_circullum_circullum` (`parent_id` ASC)
;

ALTER TABLE `circullum` 
 ADD INDEX `IXFK_circullum_lessons` (`lesson_id` ASC)
;

ALTER TABLE `cq_info` 
 ADD INDEX `IXFK_cq_info_circullum` (`c_id` ASC)
;

ALTER TABLE `cq_info` 
 ADD INDEX `IXFK_cq_info_questions` (`q_id` ASC)
;

ALTER TABLE `ei_infos` 
 ADD INDEX `IXFK_ei_infos_exams` (`e_id` ASC)
;

ALTER TABLE `ei_infos` 
 ADD INDEX `IXFK_ei_infos_institutions` (`i_id` ASC)
;

ALTER TABLE `eq_infos` 
 ADD INDEX `IXFK_eq_info_assessments` (`exam_id` ASC)
;

ALTER TABLE `eq_infos` 
 ADD INDEX `IXFK_eq_info_lessons` (`lesson_id` ASC)
;

ALTER TABLE `exam_type` 
 ADD INDEX `IXFK_exam_type_exams` (`id` ASC)
;

ALTER TABLE `exams` 
 ADD INDEX `IXFK_exams_exam_type` (`type_id` ASC)
;

ALTER TABLE `ig_infos` 
 ADD INDEX `IXFK_ig_infos_groups` (`g_id` ASC)
;

ALTER TABLE `ig_infos` 
 ADD INDEX `IXFK_ig_infos_institutions` (`i_id` ASC)
;

ALTER TABLE `sc_infos` 
 ADD INDEX `IXFK_sc_infos_choices` (`c_id` ASC)
;

ALTER TABLE `sc_infos` 
 ADD INDEX `IXFK_sc_infos_exams` (`e_id` ASC)
;

ALTER TABLE `sc_infos` 
 ADD INDEX `IXFK_sc_infos_questions` (`q_id` ASC)
;

ALTER TABLE `sc_infos` 
 ADD INDEX `IXFK_sc_infos_students` (`s_id` ASC)
;

ALTER TABLE `students` 
 ADD INDEX `IXFK_students_institutions` (`inst_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `choices` 
 ADD CONSTRAINT `FK_choices_questions`
	FOREIGN KEY (`q_id`) REFERENCES `questions` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `circullum` 
 ADD CONSTRAINT `FK_circullum_circullum`
	FOREIGN KEY (`parent_id`) REFERENCES `circullum` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `circullum` 
 ADD CONSTRAINT `FK_circullum_lessons`
	FOREIGN KEY (`lesson_id`) REFERENCES `lessons` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `cq_info` 
 ADD CONSTRAINT `FK_cq_info_circullum`
	FOREIGN KEY (`c_id`) REFERENCES `circullum` (`id`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `cq_info` 
 ADD CONSTRAINT `FK_cq_info_questions`
	FOREIGN KEY (`q_id`) REFERENCES `questions` (`id`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `ei_infos` 
 ADD CONSTRAINT `FK_ei_infos_exams`
	FOREIGN KEY (`e_id`) REFERENCES `exams` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ei_infos` 
 ADD CONSTRAINT `FK_ei_infos_institutions`
	FOREIGN KEY (`i_id`) REFERENCES `institutions` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `eq_infos` 
 ADD CONSTRAINT `FK_eq_info_assessments`
	FOREIGN KEY (`exam_id`) REFERENCES `exams` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `eq_infos` 
 ADD CONSTRAINT `FK_eq_info_lessons`
	FOREIGN KEY (`lesson_id`) REFERENCES `lessons` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `exams` 
 ADD CONSTRAINT `FK_exams_exam_type`
	FOREIGN KEY (`type_id`) REFERENCES `exam_type` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ig_infos` 
 ADD CONSTRAINT `FK_ig_infos_groups`
	FOREIGN KEY (`g_id`) REFERENCES `groups` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `ig_infos` 
 ADD CONSTRAINT `FK_ig_infos_institutions`
	FOREIGN KEY (`i_id`) REFERENCES `institutions` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `sc_infos` 
 ADD CONSTRAINT `FK_sc_infos_choices`
	FOREIGN KEY (`c_id`) REFERENCES `choices` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `sc_infos` 
 ADD CONSTRAINT `FK_sc_infos_exams`
	FOREIGN KEY (`e_id`) REFERENCES `exams` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `sc_infos` 
 ADD CONSTRAINT `FK_sc_infos_questions`
	FOREIGN KEY (`q_id`) REFERENCES `questions` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `sc_infos` 
 ADD CONSTRAINT `FK_sc_infos_students`
	FOREIGN KEY (`s_id`) REFERENCES `students` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `students` 
 ADD CONSTRAINT `FK_students_institutions`
	FOREIGN KEY (`inst_id`) REFERENCES `institutions` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
